"""returned_at column added to rent model

Revision ID: 3cf55f783b6a
Revises: f090dead9ae8
Create Date: 2026-03-30 16:44:41.361635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cf55f783b6a'
down_revision: Union[str, Sequence[str], None] = 'f090dead9ae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rents', sa.Column('returned_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rents', 'returned_at')
    # ### end Alembic commands ###
