"""update user model for mobile app

Revision ID: 708110c72e2a
Revises: 
Create Date: 2026-03-13 11:47:49.390213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '708110c72e2a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_tenant_type_size'), table_name='products')
    op.drop_index(op.f('ix_renter_tenant_phone'), table_name='renter')
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_phone_verified', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_users_tenant_telegram'), table_name='users')
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.create_index(op.f('ix_users_tenant_telegram'), 'users', ['tenant_id', 'telegram_id'], unique=False)
    op.drop_column('users', 'is_phone_verified')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'password_hash')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.create_index(op.f('ix_renter_tenant_phone'), 'renter', ['tenant_id', 'renter_phone_number'], unique=False)
    op.create_index(op.f('ix_product_tenant_type_size'), 'products', ['tenant_id', 'product_type', 'product_size'], unique=False)
    # ### end Alembic commands ###
