"""add user_id column for renter table

Revision ID: 82e2aeebb3bb
Revises: 6f1993f25626
Create Date: 2026-03-25 12:16:01.700631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82e2aeebb3bb'
down_revision: Union[str, Sequence[str], None] = '6f1993f25626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('renter', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_renter_user_id'), 'renter', ['user_id'], unique=False)
    op.create_foreign_key(None, 'renter', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'renter', type_='foreignkey')
    op.drop_index(op.f('ix_renter_user_id'), table_name='renter')
    op.drop_column('renter', 'user_id')
    # ### end Alembic commands ###
