"""add new column to user for location

Revision ID: de7481706696
Revises: 82e2aeebb3bb
Create Date: 2026-03-25 16:44:46.548097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de7481706696'
down_revision: Union[str, Sequence[str], None] = '82e2aeebb3bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('warehouse_latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('warehouse_longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'warehouse_longitude')
    op.drop_column('users', 'warehouse_latitude')
    # ### end Alembic commands ###
