"""add new column to renter for delete

Revision ID: f090dead9ae8
Revises: de7481706696
Create Date: 2026-03-25 20:21:06.857509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f090dead9ae8'
down_revision: Union[str, Sequence[str], None] = 'de7481706696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('renter', sa.Column('renter_is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('renter', 'renter_is_active')
    # ### end Alembic commands ###
